version_maps = {
    "真": ["maimai PLUS", "maimai"],
    "超": ["maimai GreeN"],
    "檄": ["maimai GreeN PLUS"],
    "橙": ["maimai ORANGE"],
    "暁": ["maimai ORANGE PLUS"],
    "晓": ["maimai ORANGE PLUS"],
    "桃": ["maimai PiNK"],
    "櫻": ["maimai PiNK PLUS"],
    "樱": ["maimai PiNK PLUS"],
    "紫": ["maimai MURASAKi"],
    "菫": ["maimai MURASAKi PLUS"],
    "堇": ["maimai MURASAKi PLUS"],
    "懂": ["maimai MURASAKi PLUS"],
    "白": ["maimai MiLK"],
    "雪": ["MiLK PLUS"],
    "輝": ["maimai FiNALE"],
    "辉": ["maimai FiNALE"],
    "熊": ["舞萌DX"],
    "華": ["舞萌DX"],
    "华": ["舞萌DX"],
    "爽": ["舞萌DX 2021"],
    "煌": ["舞萌DX 2021"],
    "宙": ["舞萌DX 2022"],
    "星": ["舞萌DX 2022"],
    "祭": ["舞萌DX 2023"],
    "祝": ["舞萌DX 2023"],
    "舞": ["maimai PLUS", "maimai", "maimai GreeN", "maimai GreeN PLUS", "maimai ORANGE", "maimai ORANGE PLUS","maimai PiNK", "maimai PiNK PLUS", "maimai MURASAKi", "maimai MURASAKi PLUS", "maimai MiLK", "MiLK PLUS","maimai FiNALE"],
    "霸": ["maimai PLUS", "maimai", "maimai GreeN", "maimai GreeN PLUS", "maimai ORANGE", "maimai ORANGE PLUS","maimai PiNK", "maimai PiNK PLUS", "maimai MURASAKi", "maimai MURASAKi PLUS", "maimai MiLK", "MiLK PLUS","maimai FiNALE"]
}

ALL_VERSION_LIST = ["maimai PLUS","maimai","maimai GreeN","maimai GreeN PLUS","maimai ORANGE","maimai ORANGE PLUS","maimai PiNK","maimai PiNK PLUS","maimai MURASAKi","maimai MURASAKi PLUS","maimai MiLK","MiLK PLUS","maimai FiNALE","maimai でらっくす","maimai でらっくす FESTiVAL","maimai でらっくす UNiVERSE","maimai でらっくす Splash"]